services:

  db: 
    container_name: 'Database'
    image: 'postgres:16-alpine'
    ports: 
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
        - rede_local

  migrate:
    build:
      context: ./Backend/Express
    command: sh -c "sleep 5 && npx prisma migrate deploy"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - rede_local
      
  api:
    container_name: 'Express_api'
    depends_on: 
    - db
    - migrate
    build:
      context: ./Backend/Express
      dockerfile: Dockerfile
    ports: 
      - '5000:5000'
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - rede_local
    env_file:
      - .env
      
  chatbot:
    container_name: 'ChatBot'
    depends_on: 
    - api
    build:
      context: ./Backend/FastAPI
      dockerfile: Dockerfile
    ports: 
      - '3000:3000'
    networks:
      - rede_local

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - rede_local

  frontend:
    container_name: front
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      -  ./Frontend:/src
      - /src/node_modules
    depends_on:
      - api
    networks:
      - rede_local

volumes:
  postgres_data:

networks:
  rede_local:
    driver: bridge
